theme: jekyll-theme-cayman
title: Business Central Apps
description: Open-source Business Central extensions by walter75 Consulting
show_downloads: true

# Include subdirectories for rendering
include:
  - docs/

# Exclude app build artifacts and source code
exclude:
  - "*.app"
  - "*.flf"
  - src/
  - Translations/
  - .ressources/
  - app.json
  - CHANGELOG.md 
